spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}

logging:
  level:
    com.campushanjang: INFO
  file:
    name: logs/app.log
